WITH PARENT_CHILD_TABLE AS (
    SELECT
        PARENT_ITEM_ID AS PARENT_ITEM_ID,
        COUNT(*) AS CHILD_COUNT
    FROM
        ITEM_TREE
    GROUP BY
        PARENT_ITEM_ID
)

SELECT
    I.ITEM_ID,
    I.ITEM_NAME,
    I.RARITY
FROM
    ITEM_INFO I
LEFT OUTER JOIN
    PARENT_CHILD_TABLE P ON I.ITEM_ID = P.PARENT_ITEM_ID
WHERE
    P.CHILD_COUNT IS NULL
ORDER BY
    I.ITEM_ID DESC
