WITH PARENT_CHILD_TABLE AS (
    SELECT
        PARENT_ID,
        COUNT(*) AS CHILD_COUNT
    FROM
        ECOLI_DATA
    GROUP BY
        PARENT_ID
)

SELECT 
    E.ID,
    IFNULL(P.CHILD_COUNT, 0) AS CHILD_COUNT
FROM
    ECOLI_DATA E
LEFT OUTER JOIN
    PARENT_CHILD_TABLE P ON E.ID = P.PARENT_ID
ORDER BY
    E.ID
