WITH PRODUCT_AMOUNT AS (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM
        OFFlINE_SALE
    GROUP BY
        PRODUCT_ID
)

SELECT
    PRODUCT_CODE,
    (P.PRICE * A.TOTAL_AMOUNT) AS SALES
FROM
    PRODUCT P
JOIN
    PRODUCT_AMOUNT A ON P.PRODUCT_ID = A.PRODUCT_ID
ORDER BY
    SALES DESC, P.PRODUCT_CODE