SELECT
    CONCAT(FLOOR((MONTH(DIFFERENTIATION_DATE) - 1) / 3) + 1, 'Q') AS QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM
    ECOLI_DATA
GROUP BY
    QUARTER
ORDER BY
    QUARTER

# 1 2 3
# 4 5 6
# 7 8 9
# 10 11 12