WITH MAX_FISH_TABLE AS (
    SELECT
        I.FISH_TYPE AS FISH_TYPE,
        MAX(I.LENGTH) AS MAX_LENGTH
    FROM
        FISH_INFO I
    JOIN
        FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY
        FISH_TYPE
)

SELECT
    I.ID,
    N.FISH_NAME,
    I.LENGTH AS LENGTH
FROM
    FISH_INFO I
JOIN
    FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN
    MAX_FISH_TABLE M ON I.FISH_TYPE = M.FISH_TYPE
WHERE
    I.FISH_TYPE = M.FISH_TYPE AND I.LENGTH = M.MAX_LENGTH
ORDER BY
    I.ID
    