WITH EMPLOYEE_TOTAL_SCORE AS (
    SELECT
        EMP_NO,
        SUM(SCORE) AS TOTAL_SCORE
    FROM
        HR_GRADE
    WHERE
        YEAR = 2022
    GROUP BY
        EMP_NO
)

SELECT
    T.TOTAL_SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM
    EMPLOYEE_TOTAL_SCORE T
JOIN
    HR_EMPLOYEES E ON T.EMP_NO = E.EMP_NO
WHERE
    T.TOTAL_SCORE = (SELECT MAX(TOTAL_SCORE) FROM EMPLOYEE_TOTAL_SCORE)
ORDER BY T.TOTAL_SCORE